SQLAlchemy
AndreyGolovin85/Flask_Dp_TelegramHelpDesk pull request #14
Opened 2024-06-27 16:58 UTC by SoraAki000

Переход к использованию SQLite

2024-06-27 17:02 UTC, SoraAki000 commented on bot/bot.db
бд добавлена для примера, внутри 2 записи
![изображение](https://github.com/AndreyGolovin85/Flask_Dp_TelegramHelpDesk/assets/31774486/8ad8d34e-f1c9-4461-a6f4-65257d633935)

2024-07-02 11:59 UTC, lwof requested changes

2024-07-02 11:59 UTC, lwof commented on bot/bot.py
> +@dispatcher.callback_query(lambda call: call.data.startswith("accept_ticket:"))
А здесь нельзя фильтр переписать, что бы использовать `F`? Было бы более унифицированно.

2024-07-02 11:59 UTC, lwof commented on bot/db.py
> +with Session(bind=engine) as session:
Не уверен что это хорошее решение все функции оборачивать в одну сессию. Мне вообще кажется что оно не должно работать так 🤯

2024-07-02 11:59 UTC, lwof commented on bot/bot.py
> +    # Требуется переделать.
Оставляешь туду, опиши полность что надо сделать. Можно создать тикет, а сюда добавить ссылку на тикет.

2024-07-02 11:59 UTC, lwof commented on bot/db.py
> +with Session(bind=engine) as session:
Собственно что бы чуть улучшить код здесь, можно либо сделать класс в котором будет жить логика доступа к БД. И  add_ticket, edit_ticket_status - будут методами. 
И сохранить  session_maker как атрибут, а внутри методов уже писать 
```python
with self.session:
    seld.do_work()
```

2024-07-02 11:59 UTC, lwof commented on bot/db.py
> +with Session(bind=engine) as session:
Кстати подозреваю что тут уже не надо передавать  bind=engine в Session

2024-07-02 11:59 UTC, lwof commented on bot/db.py
> +with Session(bind=engine) as session:
Мы хотим что бы у нас была отдельная сессия на каждый реквест который мы обрабатываем. Возможно можно использовать что-то из aiogram, если они предоставляют какой-то глобальный стейт для реквеста. Надо посмотреть в документации есть ли  в aiogrom что-то вроде flask.g. Если нет, то тогда как-то руками, с классом делать это.

2024-07-02 12:22 UTC, SoraAki000 commented on bot/bot.py
> +    # Требуется переделать.
это заметка Андрея

2024-07-02 12:39 UTC, SoraAki000 commented on bot/db.py
> +with Session(bind=engine) as session:
убрал передачу...

2024-07-02 12:42 UTC, SoraAki000 commented on bot/bot.py
> +@dispatcher.callback_query(lambda call: call.data.startswith("accept_ticket:"))
я не трогал эту часть, вопрос к Андрею...

2024-07-02 12:48 UTC, SoraAki000 commented on bot/db.py
> +with Session(bind=engine) as session:
переделал функции в методы класса тикет

2024-07-02 14:21 UTC, lwof requested changes
Порядком лучше, но все еще с сессией не здорово получилось

2024-07-02 14:21 UTC, lwof commented on bot/bot.py
> +@dispatcher.callback_query(lambda call: call.data.startswith("accept_ticket:"))
А, ок. Вижу зеленый код - думаю что он новый.

2024-07-02 14:21 UTC, lwof commented on bot/db.py
> +        session.add(new_ticket)
Сейчас очень неявно используешь переменную объявленную в  top-level of module. Это  запутывает так как первая мысль тут, а что за session.

Если хочешь пойти по этой дорожке (иметь эти методы в классе Ticket) то единственное приемлемое   - это передавать session как аргумент. Эта техника называется dependency injection, та самая  D в SOLID.

2024-07-02 14:21 UTC, lwof commented on bot/db.py
> +    @staticmethod
Я бы сказал что он classmethod,  тогда надо еще указать элемент cls. 

И просто держи в голове на будущее, что возможно все равно будем эти методы рефакторить в отдельный класс.

2024-07-02 14:53 UTC, SoraAki000 commented on bot/db.py
> +    @staticmethod
хорошо, я взял статик по рекомендации иде

2024-07-02 19:07 UTC, lwof requested changes

2024-07-02 19:07 UTC, lwof commented on bot/db.py
> +engine = create_engine("sqlite:///bot.db", echo=True)
Вот эти три строчки надо перенести выше объявления таблицы (Tickets)

2024-07-02 20:23 UTC, merged