Отмена тикетов
AndreyGolovin85/Flask_Dp_TelegramHelpDesk pull request #19
Opened 2024-07-08 13:46 UTC by SoraAki000

- Добавлена возможность отмены тикетов с обеих сторон: для админа на кнопке, со стороны пользователя - командой /cancel
- Использование `/cancel` без аргументов выведет список _активных_ тикетов данного пользователя, т.е. имеющие статус **"new"** или **"in_work"**, статусы **"rejected"** и **"completed"** в выводе не видны
- Встроены проверки на существование тикета с переданным номером и наличие активных тикетов

2024-07-08 21:01 UTC, lwof requested changes
По  типу Literal не так важно. 

А вот с TicketDict, надо пофиксить проблему (или убедиться что ее нет)

2024-07-08 21:01 UTC, lwof commented on bot/bot.py
> +def buttons_keyboard(ticket_id: int, keyboard_type: int = 0) -> types.InlineKeyboardMarkup:
Чекнул документацию майпая, да, как я и говорил нам нужен  Literal, что бы указать что это строка с одним из следующих значений. 
Вот пример
https://mypy.readthedocs.io/en/stable/literal_types.html#:~:text=PrimaryColors%20%3D%20Literal%5B%22red%22%2C%20%22blue%22%2C%20%22yellow%22%5D
Если возникнут сложности с этим, сразу справшивай. Это на самом деле супер простая штука.

2024-07-08 21:01 UTC, lwof commented on bot/utils.py
> +        f"ID пользователя: {item.user_uid}",
Но ведь если item  будет не None, а типа  TicketDict, ты из него не сможешь по атрибуту вытащить. Тут ошибка будет. И пайчарм это должен бы подсвечивать...

2024-07-08 21:01 UTC, lwof commented on bot/utils.py
> +        f"ID пользователя: {item.user_uid}",
Собственно что бы это "элегантно" пофиксить, добавь к тикету метод  `def as_dict(self)`

2024-07-14 16:43 UTC, lwof requested changes
Слишком большой ПР. Я что-то поревьюил, но у меня нет ощущения что я полностью понял твой код, просто из-за большого количества изменений. Постарайся в будущем делать ПР меньшими и сфокусированными на одной проблеме. 

В этом ПР вижу довольно много кода не имеющего прямого отношения к отмене тикетов.

2024-07-14 16:43 UTC, lwof commented on bot/bot.py
> +    sys.exit(1)
Добавь тогда еще и сообщение о том чего не хватает и как это добавить. Можно ссылку на ридми репозитория например использовать. 

Если программа молча завершается, без ошибки и без какого либо сообщения - это не понятно.

2024-07-14 16:43 UTC, lwof commented on bot/bot.py
> +    if not (ticket := get_ticket_by_id(int(ticket_id))):
Или убери валрус, или надо добавить к проекту pyproject.toml, и указать минимальную версию питона. И в ридми тоже написать что нужна версия не ниже чем. 

Но можно и убрать валрус.

2024-07-14 16:43 UTC, lwof commented on bot/custom_types.py
> +class TicketIdDict(TicketDict):
ну нет, два отдельных типа тут не стоит использовать. 

Может все таки сделать id Optional?

2024-07-14 16:43 UTC, lwof commented on bot/db.py
> +        init=False,
Зачем нужны аргементы init, sort_order, use_existing_column?

Index не нужен, так как для primary_key индекс и так создастся. 
Autoincrement не нужен, так как для primary_key, оно и так будет автоинкрементом. 

Чем меньше деталей ты прибил гвоздями - тем лучше.

2024-07-14 16:43 UTC, lwof commented on bot/db.py
> +    id: Mapped[int] = mapped_column(
Я понимаю что мы МОЖЕМ вынести id в бэйз, но мне кажется что это увеличивает сложность кода, потому что когда ты смотришь на определение класса  User, надо еще помнить что в Base объявлен  id.
Меньшее количество строчек кода, не означает "проще" 😢 увы

2024-07-14 16:43 UTC, lwof commented on bot/db.py
> +async def edit_ticket_status(
нет причин ей быть  async

2024-07-14 16:43 UTC, lwof commented on bot/db.py
> +async def add_ticket(ticket_dict: TicketDict) -> int:
Async тут не нужен.

2024-07-14 16:43 UTC, lwof commented on bot/db.py
> +async def add_user(user_dict: UserDict) -> User:
Асинк не нужен

2024-07-14 16:43 UTC, lwof commented on bot/custom_types.py
> +class UserDict(BaseModel):
Это не Dict. Можно назвать его UserDTO например, но это точно не дикт.

2024-07-14 16:43 UTC, lwof commented on bot/db.py
> +async def add_ticket(ticket_dict: TicketDict) -> int:
Проверь остальные функции подобные. Им не зачем быть асинк.

2024-07-14 19:01 UTC, SoraAki000 commented on bot/custom_types.py
> +class TicketIdDict(TicketDict):
я пробовал, это код ломает

2024-07-14 19:54 UTC, merged