Команды для создания и вывода тикетов
AndreyGolovin85/Flask_Dp_TelegramHelpDesk pull request #5
Opened 2024-06-14 06:37 UTC by SoraAki000

- Создана команда new_ticket для добавления нового тикета в виде списка
- Создана команда tickets которая выводит тикеты в отдельных сообщениях
- Примеры ввода/вывода на скриншоте
![изображение](https://github.com/AndreyGolovin85/Flask_Dp_TelegramHelpDesk/assets/31774486/eed78d12-378f-46a7-b431-333711223244)

2024-06-14 06:53 UTC, SoraAki000 commented on bot/bot.py
Забыл тестовый принт убрать -_-ь

2024-06-18 11:13 UTC, lwof requested changes

2024-06-18 11:13 UTC, lwof commented on bot/bot.py
> +            f"User ID: {tickets[-1]['user_id']}",
перед началом  as_list, вытащи в отдельную переменную `last_ticket = tickets[-1]`
рефакторинг пайчарма должен хорошо с этим справиться. 
выделить tickets[-1], клик правой кнопкой мыши, Refactoring - Define variable

2024-06-18 11:13 UTC, lwof commented on bot/bot.py
> +        reply = as_list(
я бы вынес это в функцию вроде render_ticket, и в обоих местах переиспользовать. Но может стоит не спешить с этим.

2024-06-18 11:15 UTC, SoraAki000 commented on bot/bot.py
> +            f"User ID: {tickets[-1]['user_id']}",
я немного переделал этот момент уже в новой ветке

2024-06-18 11:17 UTC, SoraAki000 commented on bot/bot.py
> +        reply = as_list(
изменю в новой ветке...

2024-06-18 11:17 UTC, merged