Добавил уведомления для админа
AndreyGolovin85/Flask_Dp_TelegramHelpDesk pull request #9
Opened 2024-06-18 20:50 UTC by AndreyGolovin85

2024-06-19 19:30 UTC, lwof requested changes
А как можно сделать так, что бы админу прилетало уведомление в момент когда создается новая заявка?

2024-06-19 19:30 UTC, lwof commented on bot/bot.py
> +async def check_tickets(tickets_new):
Нет никакой нужды делать ее асинк. Преврати в обычную.

2024-06-20 05:33 UTC, AndreyGolovin85 commented on bot/bot.py
> +async def check_tickets(tickets_new):
Исправил.

2024-06-22 16:12 UTC, lwof approved these changes
Да, похоже на то что нужно!

2024-06-22 20:13 UTC, merged